apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modelserves.model.example.com
spec:
  group: model.example.com
  names:
    kind: ModelServe
    listKind: ModelServeList
    plural: modelserves
    singular: modelserve
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              modelName:
                type: string
              modelUrl:
                type: string
              replicas:
                type: integer
              image:
                type: string
          status:
            type: object
            properties:
              availableReplicas:
                type: integer
    subresources:
      status: {}
