apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inference-operator-role
rules:
- apiGroups: ["model.example.com"]
  resources: ["modelserves"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["model.example.com"]
  resources: ["modelserves/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inference-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inference-operator-role
subjects:
- kind: ServiceAccount
  name: inference-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-operator
  template:
    metadata:
      labels:
        app: inference-operator
    spec:
      serviceAccountName: inference-operator
      containers:
      - name: manager
        image: inference-operator:latest
        imagePullPolicy: Never
        env:
        - name: WATCH_NAMESPACE
          value: "default"
        - name: ENABLE_WEBHOOKS
          value: "false"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: inference-config
              key: DATABASE_URL
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: inference-config
              key: MINIO_ENDPOINT
        - name: MINIO_BUCKET
          valueFrom:
            configMapKeyRef:
              name: inference-config
              key: MINIO_BUCKET
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: inference-secrets
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: inference-secrets
              key: MINIO_SECRET_KEY
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
