apiVersion: v1
kind: ServiceAccount
metadata:
  name: contract-service
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contract-service-role
rules:
  - apiGroups: ["inference.zeroops.io", "model.example.com"]
    resources: ["modelserves"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["traefik.io"]
    resources: ["middlewares"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contract-service-rolebinding
subjects:
  - kind: ServiceAccount
    name: contract-service
    namespace: default
roleRef:
  kind: ClusterRole
  name: contract-service-role
  apiGroup: rbac.authorization.k8s.io
